[I 18:28:24.925 NotebookApp] Serving notebooks from local directory: /home/ubuntu/Python-Notebook
[I 18:28:24.925 NotebookApp] Jupyter Notebook 6.5.3 is running at:
[I 18:28:24.925 NotebookApp] http://VM-12-9-ubuntu:8888/
[I 18:28:24.925 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 18:28:39.397 NotebookApp] 302 GET / (171.43.236.71) 0.450000ms
[W 18:30:22.568 NotebookApp] Forbidden
[W 18:30:22.568 NotebookApp] 403 GET /api/contents?type=directory&_=1679048919864 (180.101.244.11) 0.740000ms referer=http://114.132.78.107:8888/tree?
[W 18:30:41.641 NotebookApp] Notebook matplotlib/matplotlib.ipynb is not trusted
[I 18:30:45.717 NotebookApp] Kernel started: 47746fda-9cb3-4c94-9b05-98a7d44dc36b, name: python3
[I 18:31:24.574 NotebookApp] Starting buffering for 47746fda-9cb3-4c94-9b05-98a7d44dc36b:695ac1f9d462403b8eb6845b86e93f44
[I 18:32:30.442 NotebookApp] 302 GET / (171.43.236.71) 0.420000ms
[W 18:33:06.114 NotebookApp] Forbidden
[W 18:33:06.114 NotebookApp] 403 GET /api/contents?type=directory&_=1679048921378 (59.83.208.106) 0.710000ms referer=http://114.132.78.107:8888/tree?
[I 18:33:10.294 NotebookApp] 302 GET / (171.43.236.71) 0.400000ms
[I 18:33:10.320 NotebookApp] 302 GET /tree? (171.43.236.71) 0.630000ms
[W 18:33:55.351 NotebookApp] Forbidden
[W 18:33:55.351 NotebookApp] 403 GET /api/config/tree?_=1679048919859 (180.101.245.250) 0.710000ms referer=http://114.132.78.107:8888/tree?
[W 18:34:18.020 NotebookApp] Forbidden
[W 18:34:18.020 NotebookApp] 403 GET /api/terminals?_=1679048919863 (220.196.160.151) 0.690000ms referer=http://114.132.78.107:8888/tree?
[W 18:34:29.171 NotebookApp] Couldn't authenticate WebSocket connection
[W 18:34:29.176 NotebookApp] 403 GET /api/kernels/47746fda-9cb3-4c94-9b05-98a7d44dc36b/channels?session_id=695ac1f9d462403b8eb6845b86e93f44 (220.196.160.95) 5.680000ms referer=None
[W 18:37:30.931 NotebookApp] Forbidden
[W 18:37:30.932 NotebookApp] 403 GET /api/contents/matplotlib/matplotlib.ipynb?type=notebook&_=1679049041267 (180.101.245.250) 0.770000ms referer=http://114.132.78.107:8888/notebooks/matplotlib/matplotlib.ipynb
[W 18:38:10.593 NotebookApp] Forbidden
[W 18:38:10.593 NotebookApp] 403 GET /api/terminals?_=1679049150591 (220.196.160.45) 0.660000ms referer=http://114.132.78.107:8888/tree?
[W 18:38:49.846 NotebookApp] Forbidden
[W 18:38:49.846 NotebookApp] 403 GET /api/config/common?_=1679048919860 (180.101.245.248) 0.770000ms referer=http://114.132.78.107:8888/tree?
[I 18:39:06.334 NotebookApp] 302 GET /edit/push_to_github.log (220.196.160.84) 0.670000ms
[W 18:39:08.576 NotebookApp] Forbidden
[W 18:39:08.576 NotebookApp] 403 GET /api/sessions?_=1679048922584 (180.101.244.16) 0.700000ms referer=http://114.132.78.107:8888/tree?
[W 18:39:28.753 NotebookApp] Forbidden
[W 18:39:28.753 NotebookApp] 403 GET /api/config/edit?_=1679049240215 (59.83.208.108) 0.740000ms referer=http://114.132.78.107:8888/edit/push_to_github.log
[W 18:39:38.114 NotebookApp] Forbidden
[W 18:39:38.114 NotebookApp] 403 GET /api/contents/matplotlib?type=directory&_=1679049037181 (220.196.160.154) 0.730000ms referer=http://114.132.78.107:8888/tree/matplotlib
[W 18:40:14.265 NotebookApp] Forbidden
[W 18:40:14.265 NotebookApp] 403 GET /api/config/notebook?_=1679049041265 (220.196.160.65) 0.670000ms referer=http://114.132.78.107:8888/notebooks/matplotlib/matplotlib.ipynb
[W 18:40:23.193 NotebookApp] Forbidden
[W 18:40:23.193 NotebookApp] 403 GET /api/contents?type=directory&_=1679048922586 (180.101.244.12) 0.760000ms referer=http://114.132.78.107:8888/tree?
[W 18:40:36.334 NotebookApp] Forbidden
[W 18:40:36.334 NotebookApp] 403 GET /api/contents/push_to_github.log?type=file&format=text&_=1679049240217 (220.196.160.96) 0.790000ms referer=http://114.132.78.107:8888/edit/push_to_github.log
[W 18:41:57.675 NotebookApp] Forbidden
[W 18:41:57.675 NotebookApp] 403 GET /api/config/common?_=1679049150588 (59.83.208.103) 0.810000ms referer=http://114.132.78.107:8888/tree?
[W 18:42:01.575 NotebookApp] Forbidden
[W 18:42:01.575 NotebookApp] 403 GET /api/contents/matplotlib/matplotlib.ipynb/checkpoints?_=1679049041268 (220.196.160.101) 0.790000ms referer=http://114.132.78.107:8888/notebooks/matplotlib/matplotlib.ipynb
[W 18:43:24.366 NotebookApp] Forbidden
[W 18:43:24.366 NotebookApp] 403 GET /api/contents/matplotlib?type=directory&_=1679049037184 (180.101.245.250) 0.760000ms referer=http://114.132.78.107:8888/tree/matplotlib
[W 18:44:21.989 NotebookApp] Forbidden
[W 18:44:21.989 NotebookApp] 403 GET /api/terminals?_=1679049150597 (220.196.160.61) 0.680000ms referer=http://114.132.78.107:8888/tree?
[W 18:58:38.489 NotebookApp] Forbidden
[W 18:58:38.489 NotebookApp] 403 GET /api/config/common?_=1679050570994 (180.101.244.13) 0.730000ms referer=http://114.132.78.107:8888/tree?
[W 18:59:07.154 NotebookApp] Forbidden
[W 18:59:07.155 NotebookApp] 403 GET /api/sessions?_=1679049150602 (180.101.244.15) 0.810000ms referer=http://114.132.78.107:8888/tree?
[W 19:00:59.644 NotebookApp] Forbidden
[W 19:00:59.644 NotebookApp] 403 GET /api/contents?type=directory&_=1679049150604 (180.101.244.13) 0.720000ms referer=http://114.132.78.107:8888/tree?
[W 19:04:35.103 NotebookApp] Forbidden
[W 19:04:35.103 NotebookApp] 403 GET /api/config/tree?_=1679050570993 (59.83.208.108) 0.770000ms referer=http://114.132.78.107:8888/tree?
[W 19:04:40.247 NotebookApp] Forbidden
[W 19:04:40.247 NotebookApp] 403 GET /api/terminals?_=1679050570995 (59.83.208.107) 0.670000ms referer=http://114.132.78.107:8888/tree?
[W 20:09:31.459 NotebookApp] Forbidden
[W 20:09:31.460 NotebookApp] 403 GET /api/config/common?_=1679043409136 (180.101.245.247) 0.830000ms referer=http://114.132.78.107:8888/tree?
[I 20:11:40.340 NotebookApp] 302 GET / (171.43.236.71) 0.410000ms
[W 20:14:12.033 NotebookApp] Forbidden
[W 20:14:12.034 NotebookApp] 403 GET /api/config/tree?_=1679055105227 (59.83.208.103) 0.790000ms referer=http://114.132.78.107:8888/tree?
[W 20:14:17.141 NotebookApp] Forbidden
[W 20:14:17.141 NotebookApp] 403 GET /api/terminals?_=1679055105231 (59.83.208.106) 0.670000ms referer=http://114.132.78.107:8888/tree?
[W 20:16:28.997 NotebookApp] Forbidden
[W 20:16:28.998 NotebookApp] 403 GET /api/terminals?_=1679055105229 (180.101.244.14) 0.710000ms referer=http://114.132.78.107:8888/tree?
[W 20:18:48.773 NotebookApp] Forbidden
[W 20:18:48.773 NotebookApp] 403 GET /api/config/common?_=1679055105228 (59.83.208.106) 0.740000ms referer=http://114.132.78.107:8888/tree?
[W 20:20:41.955 NotebookApp] Forbidden
[W 20:20:41.955 NotebookApp] 403 GET /api/contents?type=directory&_=1679055105234 (220.196.160.76) 0.760000ms referer=http://114.132.78.107:8888/tree?
[W 20:22:05.738 NotebookApp] Forbidden
[W 20:22:05.738 NotebookApp] 403 GET /api/contents/matplotlib?type=directory&_=1679043977098 (220.196.160.117) 0.750000ms referer=http://114.132.78.107:8888/tree/matplotlib
[W 20:22:52.685 NotebookApp] Forbidden
[W 20:22:52.685 NotebookApp] 403 GET /api/contents/test?type=directory&_=1679043633907 (220.196.160.76) 0.800000ms referer=http://114.132.78.107:8888/tree/test
[W 20:29:41.093 NotebookApp] Forbidden
[W 20:29:41.093 NotebookApp] 403 GET /api/contents?type=directory&_=1679043977102 (59.83.208.103) 0.730000ms referer=http://114.132.78.107:8888/tree
[W 20:38:22.111 NotebookApp] Forbidden
[W 20:38:22.111 NotebookApp] 403 GET /api/contents/pandas/data_r.csv?type=file&format=text&_=1679044599054 (220.196.160.125) 0.770000ms referer=http://114.132.78.107:8888/edit/pandas/data_r.csv
[W 20:46:23.375 NotebookApp] Forbidden
[W 20:46:23.375 NotebookApp] 403 GET /api/contents/pandas?type=directory&_=1679044477339 (220.196.160.83) 0.740000ms referer=http://114.132.78.107:8888/tree/pandas
[W 20:54:42.077 NotebookApp] Forbidden
[W 20:54:42.077 NotebookApp] 403 GET /api/contents/pandas/pandas.ipynb?content=0&_=1679044589112 (180.101.245.252) 0.750000ms referer=http://114.132.78.107:8888/notebooks/pandas/pandas.ipynb
[I 21:08:04.801 NotebookApp] 302 GET / (120.211.145.96) 0.450000ms
[I 21:08:16.321 NotebookApp] 302 GET / (122.96.28.235) 0.430000ms
[I 21:08:16.446 NotebookApp] 302 GET /tree? (112.66.101.71) 0.510000ms
[W 22:32:39.847 NotebookApp] Forbidden
[W 22:32:39.847 NotebookApp] 403 GET /api/config/tree?_=1679049150587 (220.196.160.124) 0.760000ms referer=http://114.132.78.107:8888/tree?
[I 22:34:07.926 NotebookApp] 302 GET / (171.43.236.71) 0.410000ms
[W 22:34:22.991 NotebookApp] Notebook numpy/numpy.ipynb is not trusted
[I 22:34:23.747 NotebookApp] Kernel started: 4ca8c3e9-be17-47a0-ac84-674d742e32d9, name: python3
[I 22:34:31.200 NotebookApp] Starting buffering for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:a73c8446b9334a638528a8fa3e3c6417
[I 22:34:31.431 NotebookApp] Kernel restarted: 4ca8c3e9-be17-47a0-ac84-674d742e32d9
[I 22:34:31.513 NotebookApp] Restoring connection for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:a73c8446b9334a638528a8fa3e3c6417
[I 22:34:32.017 NotebookApp] Replaying 3 buffered messages
[E 22:34:32.132 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 22:34:32.134 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback BaseAsyncIOLoop._handle_events(44, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(44, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
    return callback(self, msg)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
    super()._on_zmq_reply(stream, msg)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
    self._handle_write()
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
[I 22:34:49.504 NotebookApp] Saving file at /numpy/numpy.ipynb
[W 22:34:49.565 NotebookApp] Trusting notebook /numpy/numpy.ipynb
[I 22:34:54.572 NotebookApp] Starting buffering for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:a73c8446b9334a638528a8fa3e3c6417
[I 22:34:56.163 NotebookApp] Discarding 59 buffered messages for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:a73c8446b9334a638528a8fa3e3c6417
[I 22:35:05.147 NotebookApp] Starting buffering for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:d6f6b99cc5e64a06869a8eb55849c80c
[I 22:35:05.379 NotebookApp] Kernel restarted: 4ca8c3e9-be17-47a0-ac84-674d742e32d9
[I 22:35:05.468 NotebookApp] Restoring connection for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:d6f6b99cc5e64a06869a8eb55849c80c
[I 22:35:06.473 NotebookApp] Replaying 3 buffered messages
[E 22:35:06.552 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 22:35:06.552 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 22:35:06.552 NotebookApp] Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7f14ea177130>)
    Traceback (most recent call last):
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
        ret = callback()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
        self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/ubuntu/Python-Notebook/.venv/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[I 22:35:48.857 NotebookApp] Saving file at /numpy/numpy.ipynb
[I 22:36:13.804 NotebookApp] Saving file at /numpy/numpy.ipynb
[I 22:36:41.477 NotebookApp] Starting buffering for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:d6f6b99cc5e64a06869a8eb55849c80c
[I 22:36:41.708 NotebookApp] Kernel restarted: 4ca8c3e9-be17-47a0-ac84-674d742e32d9
[I 22:36:41.768 NotebookApp] Restoring connection for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:d6f6b99cc5e64a06869a8eb55849c80c
[I 22:36:42.272 NotebookApp] Replaying 137 buffered messages
[I 22:36:54.744 NotebookApp] Saving file at /numpy/numpy.ipynb
[I 22:36:54.817 NotebookApp] Starting buffering for 4ca8c3e9-be17-47a0-ac84-674d742e32d9:d6f6b99cc5e64a06869a8eb55849c80c
[W 22:36:59.358 NotebookApp] Notebook hello.ipynb is not trusted
[I 22:36:59.596 NotebookApp] Kernel started: df5e68ff-7736-43f9-8365-2ace3e0050d9, name: python3
[W 22:37:41.205 NotebookApp] 405 GET /api/contents/numpy/numpy.ipynb/trust (59.83.208.108) 2.050000ms referer=http://114.132.78.107:8888/notebooks/numpy/numpy.ipynb
[I 22:37:42.319 NotebookApp] Saving file at /numpy/numpy.ipynb
[I 22:37:44.473 NotebookApp] Saving file at /hello.ipynb
[I 22:37:45.574 NotebookApp] Starting buffering for df5e68ff-7736-43f9-8365-2ace3e0050d9:76eb6e521a954a24b927f40e5a742a97
